"""initial schema

Revision ID: 3bf23cb33549
Revises: 
Create Date: 2026-07-04 22:12:07.712279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf23cb33549'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('telegram_sent', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_timestamp', 'alerts', ['timestamp'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('ram_total_mb', sa.Float(), nullable=False),
    sa.Column('ram_used_mb', sa.Float(), nullable=False),
    sa.Column('ram_percent', sa.Float(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('net_bytes_sent', sa.Float(), nullable=False),
    sa.Column('net_bytes_recv', sa.Float(), nullable=False),
    sa.Column('load_avg_1', sa.Float(), nullable=True),
    sa.Column('load_avg_5', sa.Float(), nullable=True),
    sa.Column('load_avg_15', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_id'), 'metric_snapshots', ['id'], unique=False)
    op.create_index('ix_metric_snapshots_timestamp', 'metric_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metric_snapshots_timestamp', table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index('ix_alerts_timestamp', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
